### ISSUE TITLE
add a slide on hand-drawn visualization to both intro and tools sections

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/data-viz-101#23]
https://docs.google.com/presentation/d/1Qk_6AEJoiK8UgCL-UJ2wsqjkK0T4YbL5Co2Q8rhBtII/edit

**Comment by grynoch** [comment]
Added slide for tools section. feel free to edit

**Comment by amzoss** [comment]
I think with David's redesign of the intro, we probably don't need to add anything on sketching, and @grynoch 's changes to the tools section look really good to me. 

@negeenaghassi , sorry it took me so long to take a look, but your data art workshop looks fabulous. I'd love to talk more about whether you'd be willing to share any of the content through the grant, either as an additional section of data viz 101 or separately (like the ethics module).
